### ISSUE TITLE
Confusion matrices

### ISSUE THREAD

**Issue by wajihullahbaig** [di37/multimodal-image-classification#3]
Adding confusion matrices can really be valuable against each LLMs output

**Comment by ishamnewsreels** [comment]
Its there in the 4th Notebook

**Comment by di37** [comment]
Its there in the 4th Notebook: https://github.com/di37/image-classification-using-multimodal-llms/blob/main/notebooks/04_Models_Evaluation.ipynb. Also explained confusion matrices in depth for the llms that doesnt have 100% accuracy in the Medium article.
